<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="Features\Chat\" />
    <Folder Include="Features\AIAssistant\" />
    <Folder Include="Features\Admin\" />
    <Folder Include="Features\Payments\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Features\Community\Posts\Commands\EditPost\EditPostCommand.cs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Riok.Mapperly" Version="4.2.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	  <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FishingCommunity.Domain\FishingCommunity.Domain.csproj" />
    <ProjectReference Include="..\FishingCommunity.Shared\FishingCommunity.Shared.csproj" />
  </ItemGroup>

</Project>
